#!/bin/bash

SIZE=${1-3}
DELAY=${2-1.0}
MAX=${3-10}
RANGE=${4-50}
BASE=10
DIFF="7 - 3"


echo 1>&2 SIZE ${SIZE}
echo 1>&2 DELAY ${DELAY}
echo 1>&2 MAX ${MAX}

i=0
while [ $i -lt ${SIZE} ] ; do
  echo -n "`echo $i | tr 0123456789 ABCDEFGHIJ` "
  i=`expr $i + 1`
done
echo ""

i=0
while [ $i -lt ${SIZE} ] ; do
  VALUE[$i]=`expr $RANDOM % ${RANGE} + ${BASE}`
  i=`expr $i + 1`
done

count=0
while [ $count -lt $MAX ] ; do 
  count=`expr $count + 1`
  i=0
  while [ $i -lt ${SIZE} ] ; do
    echo -n "${VALUE[$i]} "
    i=`expr $i + 1`
  done
  echo ""

  i=0
  while [ $i -lt ${SIZE} ] ; do
    d=`expr $RANDOM % ${DIFF}`
    VALUE[$i]=`expr ${VALUE[$i]} + ${d}`
    i=`expr $i + 1`
  done
  
  sleep ${DELAY}
done
