#!/bin/sh 

. ${PTAYLOR_HOME-/home/ptaylor}/bin/ptenv.sh

if [ $#argv -lt 1 ] ; then
    echo 1>&2 "usage: graph-ps <pid|name> [<graph-options]"
    exit 1
fi

pid=$1
shift
(
  echo "VSZ";
  while : ; 
    do
      ps -u ptaylor -o pid,comm,vsz |
	grep $pid |
	  cols 3  
      sleep 10
  done
) | graph -max -min -base 8 "$@"
