#!/bin/sh


. ${PTAYLOR_HOME-/home/ptaylor}/bin/ptenv.sh

if [ $#argv -lt 1 ] ; then
    echo 1>&2 "usage: graph-latency <hosts>"
    exit 1
fi

(
	
  echo $*	
  echo $* > graph.log

  max=1000;
  while : ; 
    do
	#	v=`latency $* | sed -e '1d' | awk ' { print $6 } '`
	v=`latency $* | sed -e '1d' | awk ' $5 < 0 { print -$5 } $5 >= 0 { print $5 } '`
         for i in $v; do  
		if [ $i -gt $max ] ; then
                    if [ `expr $max \* 500` -lt $i ] ; then
                         echo 1>&2 "WARNING bad valud value $i ($v) "
			 #v=""
		    fi
                fi
         done
	 if [ "$v" -ne "" ] ; then 
	   echo $v
           echo $v >> graph.log
         fi

      sleep 1
  done
#)
) |  graph -max -min -base 5
