#!/bin/sh 

. ${PTAYLOR_HOME-/home/ptaylor}/bin/ptenv.sh

if [ $#argv -lt 1 ] ; then
    echo 1>&2 "usage: graph-prstat <pid> [<graph-options]"
    exit 1
fi

pid=$1
shift
(
  echo "SIZE RSS";
  while : ; 
    do
      prstat 0 1 |
	grep $pid |
	  cols 3 4 
      sleep 1
  done
) |
  graph -max -min -base 8 "$@"
