#!/bin/bash
#
# MIT License
#
# Copyright (c) 2017 ptaylor
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#
#
# Produce random data for testing autograph.
#
# Usage: random-values [NUM_COLUMNS] [NUM_ROWS] [MIN_VALUE] [MAX_VALUE] [DELTA] [DELAY]
#
# 

NUM_COLUMNS=${1-3}
NUM_ROWS=${2-10000}
MIN_VALUE=${3-10}
MAX_VALUE=${4-50}
DELTA=${5-7}
DELAY=${6-0.3}

if [ ${MIN_VALUE} -gt ${MAX_VALUE} ] ; then
  echo 1>&2 "WARNING: min value must be greater than max value"
  MAX_VALUE=$MIN_VALUE
fi

echo 1>&2 DATA: ${NUM_COLUMNS} x ${NUM_ROWS} ${MIN_VALUE}..${MAX_VALUE} +/ ${DELTA} ${DELAY}s

random () {
  min=$1
  max=$2
  expr $RANDOM % \( $max + 1 - $min \) + $min
}

# Output column names
i=0
while [ $i -lt ${NUM_COLUMNS} ] ; do
  echo -n "`echo $i | tr 0123456789 ABCDEFGHIJ` "
  i=`expr $i + 1`
done
echo ""

# Initialise column values
i=0
while [ $i -lt ${NUM_COLUMNS} ] ; do
  VALUE[$i]=`random ${MIN_VALUE} ${MAX_VALUE}`
  i=`expr $i + 1`
done

count=0
while [ $count -lt ${NUM_ROWS} ] ; do 
  count=`expr $count + 1`
  i=0
  while [ $i -lt ${NUM_COLUMNS} ] ; do
    echo -n "${VALUE[$i]} "
    i=`expr $i + 1`
  done
  echo ""

  i=0
  while [ $i -lt ${NUM_COLUMNS} ] ; do
    d=`random -${DELTA} ${DELTA}`
    VALUE[$i]=`expr ${VALUE[$i]} + ${d}`
    i=`expr $i + 1`
  done
  
  sleep ${DELAY}
done
