#!/bin/bash
#
# MIT License
#
# Copyright (c) 2017 ptaylor
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#

SIZE=${1-3}
DELAY=${2-1.0}
MAX=${3-10}
RANGE=${4-50}
BASE=10
DIFF="7 - 3"


echo 1>&2 SIZE ${SIZE}
echo 1>&2 DELAY ${DELAY}
echo 1>&2 MAX ${MAX}

i=0
while [ $i -lt ${SIZE} ] ; do
  echo -n "`echo $i | tr 0123456789 ABCDEFGHIJ` "
  i=`expr $i + 1`
done
echo ""

i=0
while [ $i -lt ${SIZE} ] ; do
  VALUE[$i]=`expr $RANDOM % ${RANGE} + ${BASE}`
  i=`expr $i + 1`
done

count=0
while [ $count -lt $MAX ] ; do 
  count=`expr $count + 1`
  i=0
  while [ $i -lt ${SIZE} ] ; do
    echo -n "${VALUE[$i]} "
    i=`expr $i + 1`
  done
  echo ""

  i=0
  while [ $i -lt ${SIZE} ] ; do
    d=`expr $RANDOM % ${DIFF}`
    VALUE[$i]=`expr ${VALUE[$i]} + ${d}`
    i=`expr $i + 1`
  done
  
  sleep ${DELAY}
done
